[tool.poetry]
name = "2d-game-ai"
version = "0.2.0"
description = ""
authors = ["elliot-100 <3186037+elliot-100@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pygame-ce = "^2.3.2"

[tool.poetry.group.dev.dependencies]
black = "^23.10.1"
isort = "^5.12.0"
mypy = "^1.5.1"
pre-commit = "^3.4.0"
ruff = "^0.0.291"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
mypy = "^1.5.1"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"

[tool.mypy]
## Config file:
warn_unused_configs = true
## Disallow dynamic typing:
## Disallow the use of the dynamic 'Any' type under certain conditions.
disallow_any_unimported = true  # additional to 'strict' config
disallow_any_generics = true
disallow_subclassing_any = true
## Untyped definitions and calls:
## Configure how untyped definitions and calls are handled.
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
## None and Optional handling:
## Adjust how values of type 'None' are handled.
no_implicit_optional = true  # additional to 'strict' config
## Configuring warnings:
## Detect code that is sound but redundant or problematic.
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true  # additional to 'strict' config
## Miscellaneous strictness flags:
no_implicit_reexport = true
strict_equality = true
strict_concatenate = true
##  Configuring error messages:
## Adjust the amount of detail shown in error messages.
show_error_codes = true  # additional to 'strict' config
pretty = true  # additional to 'strict' config

[tool.ruff]
# Enable rulesets:
# flake8-ANNotations, flake8-COMmas, pyDocstyle, pycodestylE, pyFlakes,
# flake8-Future-Annotations
select = ["ANN", "COM", "D", "E", "F", "FA"]

# Ignore rules:
#  Missing type annotation for `self` in method
ignore = ["ANN101"]

[tool.ruff.pydocstyle]
convention = "numpy"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
